name: Build & Deploy Pages
run-name: Build & Deploy to GitHub Pages by @${{ github.actor }}
on:
  push:
    branches:
      - 'github-pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '^1.22.3'
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '^20.14.0'
      - run: npm install
        working-directory: typescript-src/fsck-threads/
      - run: npm run build
        working-directory: typescript-src/fsck-threads/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: web/built-ts/
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2



